### ISSUE TITLE
Semantic comparison at attribute-level

### ISSUE THREAD

**Issue by agbeltran** [FAIRsharing/json-schema-tools#24]
**Input:** dictionary with [ schema1 , context1, schema2, context2]
**Assumptions:** both schemas refer to the same entity type, and both schemas use the same semantic framework (or ontologies)
**Output**: a dictionary with
- dictionary with the mapping of arrays of properties from the two schemas
- dictionary of ignored fields (as they didn't have semantic mapping)
- percentage of coverage (TBD how we define coverage)

Investigate 
https://github.com/digitalbazaar/pyld
https://github.com/RDFLib/rdflib-jsonld

**Comment by terazus** [comment]
Forgot to close;
See commit https://github.com/FAIRsharing/json-schema-tools/commit/c754d8120f329a2be94e4ba986da66470cc559ea
