### ISSUE TITLE
Absolute coverage should return the total number of fields

### ISSUE THREAD

**Issue by agbeltran** [FAIRsharing/json-schema-tools#25]
in addition to the number of matching fields, the absolute coverage should also return the total number of fields 

https://github.com/FAIRsharing/json-schema-tools/blob/DOM-SemDiff/SemDiff/semDiff.py#L108

**Comment by terazus** [comment]
Closing: see commit https://github.com/FAIRsharing/json-schema-tools/commit/219aa100e7092b81a0464da4a6998548a9d871d8
